# Generated by Django 5.0.1 on 2024-01-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libfr', models.CharField(max_length=255)),
                ('libar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libfr', models.CharField(max_length=255)),
                ('libar', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='Grades',
            field=models.ManyToManyField(related_name='schools', to='BASE.grade'),
        ),
        migrations.AddField(
            model_name='grade',
            name='Subjects',
            field=models.ManyToManyField(related_name='grades', to='BASE.subject'),
        ),
    ]
