# Generated by Django 5.0.1 on 2024-01-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0002_grade_subject_school_grades_grade_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='Grades',
        ),
    ]
