# Generated by Django 5.0.1 on 2024-01-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0003_remove_school_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Grades',
            field=models.ManyToManyField(related_name='schools', to='BASE.grade'),
        ),
    ]
