# Generated by Django 5.0.1 on 2024-01-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0004_school_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='Grades',
        ),
    ]
