# Generated by Django 5.0.1 on 2024-01-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0006_remove_grade_subjects_content_gradesubjectcontent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GradeSubjectContent',
            new_name='GradeSubject',
        ),
    ]
