# Generated by Django 5.0.1 on 2024-01-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0007_rename_gradesubjectcontent_gradesubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='gradesubject',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='grade_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='BASE.gradesubject'),
            preserve_default=False,
        ),
    ]
