# Generated by Django 5.0.1 on 2024-01-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0008_remove_content_subject_remove_gradesubject_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
