# Generated by Django 5.0.1 on 2024-02-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0009_delete_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='SchoolType',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='BASE.schooltype'),
            preserve_default=False,
        ),
    ]
